Add video preprocessing (denoising) feature
Aharoni-Lab/mio pull request #83
Opened 2024-12-07 00:29 UTC by t-sasatani

**[STILL DRAFT]** This PR adds a denoising module for neural recording videos. It can be used offline and I think we can also use this in real-time with the `streamDaq` too.

### Processing features
- Detect broken buffers by comparing buffers with the same position buffer in the previous frame (I'm only doing mean error now, but we can also add more stastistic functions).
- Remove broken buffers by copying in the same position buffer in the previous frame.
- Spatial frequency-based filtering.
- Generate the minimum projection out of a stack of frames.

Following is an example frame that detects noisy regions and patches it with the prior frame buffer:
![image](https://github.com/user-attachments/assets/397089ae-fec3-4731-9795-0005ec315934)

### Interface
You can run this with `mio process denoise` using an [example video](https://drive.google.com/open?id=1ELoWDditmomysVo4ad8xAJDS5cpWBBvU&usp=drive_fs).
The denoising parameters and export settings can be defined with [a YAML file](https://github.com/Aharoni-Lab/miniscope-io/blob/feat-preprocess/miniscope_io/data/config/process/denoise_example.yml).
```bash
mio process denoise -i .\user_dir\test.avi -c .\miniscope_io\data\config\process\denoise_example.yml
```

### Minor changes
- Moved `VideoWriter` to `io` module because it's pretty generic, and I wanted to use it for the denoising.
- Added a `user_dir` for keeping user data.

### To do/considerations
- Finish writing the modules. Add more processing modules.
- Write tests.
- The config interface feels pretty redundant...

2024-12-10 03:37 UTC, sneakers-the-rat commented
omfg you already did it!?!??!?!?! u are so fast. cant wait to check this out!!!!!

2025-01-08 01:08 UTC, MarcelMB commented
amazing!!!! Thanks, Takuya for working on this already!

- I was wondering if replacing a broken buffer with the one from the previous frame is a good strategy. Unsure. For one broken frame that might be fine but if there is a stretch of corrupted data and we basically have the same image for seconds not sure. 

- by subtracting a minimum projection at the end I was wondering if maybe not low-intensity biological signals could eventually get lost?

- I need to understand the frequency mask a bit more to see what goes through and what is blocked.

2025-01-08 02:44 UTC, sneakers-the-rat commented
> I was wondering if replacing a broken buffer with the one from the previous frame is a good strategy. Unsure. For one broken frame that might be fine but if there is a stretch of corrupted data and we basically have the same image for seconds not sure.

agree, I think we want to drop data rather than copy data - it's scientific data after all and the numbers matter, so duplicating a frame is effectively fabricating data (even though this is not a bad strategy if we were streaming a movie and didn't care about the pixel values as much)

> by subtracting a minimum projection at the end I was wondering if maybe not low-intensity biological signals could eventually get lost?
>
> I need to understand the frequency mask a bit more to see what goes through and what is blocked.

this is a decent pair of thoughts that sort of highlights that we might want to separate cosmetic/display-oriented processing stages from signal repair stages: the frequency filtering is repairing the image, while doing the minimum projection is just for display purposes (right? i'm assuming in analysis people will want to have the full signal). 

been working through backlog of issues after the holiday and my first big chunk of work will be on mio so i'll review this and stuff this week. thanks again for this Takuya :)

2025-01-08 03:19 UTC, t-sasatani commented
Thanks for the comments! I'm stuck with other stuff at the moment but will make it ready for review and ping you guys hopefully next week. Something I kind of want to know from @sneakers-the-rat is whether the high-level structure seems mergeable to the pipeline refactor. No intention to make this really compatible because we need this now and this is an independent module but the code structure is pretty arbitrary so it might be good if there is something I can easily anchor to.

And yes, Phil mentioned too dropping broken frames will be good so that's planned (might just add an option of dropping because masking is already there). I was just too lazy to look in how processing pipelines handle this and track dropped buffers.

For the FFT and minimum projection, these are just modules so I think these just should be available whenever needed. The frequency mask might be used in actual preprocessing before CMNE pipelines but I'm not sure.
https://github.com/Aharoni-Lab/Miniscope-v4/wiki/Removing-Horizontal-Noise-from-Recordings

2025-01-10 01:31 UTC, MarcelMB commented
adding a bug here for the buffer patching
most likely due to multiple frames being corrupted after each other and the code currently always looking at the last frame to patch the next one. Resulting in loosing most of each frame for the rest of the video

files used to get this bug: invivo-20241203-1-003, invivo-20241203-3.avi

using commit:
9cd2bc3955cd36d37771ad8ea5cc0dda9c02befb


![Screenshot 2025-01-09 at 12 49 12 PM](https://github.com/user-attachments/assets/a09c953d-710f-4036-ac5c-948d3e1a8847)

2025-01-13 22:44 UTC, raymondwjang commented on mio/process/video.py
> +    def denoise(
seems like there's room for improvement in terms of SOLID, especially the [single responsibility principle](https://stackify.com/solid-design-principles/). This `denoise` method for example appears to:
1. check for module
2. read video
3. write video
4. among ~10 other functions that can/should probably be modularized.

The rule of thumb normally is that if there are more than 2-3 `if` statements in a non-c-style function, it's a symptom that it can be improved for readability and maintainability.  :)

I'd hazard a guess that a lot of these `if` blocks can be packaged into different classes and files with clearer names and more consistent formatting across methods for better recyclability.

2025-01-14 00:04 UTC, sneakers-the-rat requested changes
Alright, thanks for patience, finally got time to review this. 

Two changes I think we should for sure make before merging this:
- split out each of the processing methods into separate classes with a common API and then make the video processor class generic over those classes, details in comments. 
- unify the existing `Frame` and `Frames` classes with the new `NamedFrame` class, making separate classes for a single frame vs. collections of frames.
- have tests for all of this

The rest are perf improvements and style comments

2025-01-14 00:04 UTC, sneakers-the-rat commented on mio/process/video.py
> +
here's a good example of why we want all these things to be separable functions/classes/etc. that can work framewise - ideally this would work on demand, where we just open the UI and compute it as requested in the context of a GUI (not something `mio` should try and provide) rather than needing to precompute everything and set up a UI for it afterwards.

2025-01-14 00:04 UTC, sneakers-the-rat commented on mio/process/video.py
> +    def normalize_video_stack(image_list: list[np.ndarray]) -> list[np.ndarray]:
either should be a separate class like the other processor classes or a function, strange to have it here in a different form than all the other video processing methods.

2025-01-14 00:06 UTC, sneakers-the-rat commented on mio/process/video.py
> +    def denoise(
agreed. shouldn't be too tricky to split each of these into separate classes with an `__init__` that takes config, `process()` that applies the transform, and `finish()` (or whatever we want to call it) that handles writing output if requested.

2025-01-14 00:50 UTC, raymondwjang commented
Also would like to add that while I'm also sometimes a violator of this, each PR should ideally consist of ~10 commits, with fewer than 500 lines of codes.

@t-sasatani: Here's something that might help that @sneakers-the-rat and I presented during the lab meeting that you couldn't attend [(link)](https://docs.google.com/presentation/d/16ZRpjDD3BZndC2VmfzuZ4AtqW1c8TaRperaaUXD0MyQ/edit#slide=id.g3164360f84a_0_131)

2025-01-14 01:10 UTC, t-sasatani commented
Thanks. I'll look at these later, but could you guys hold off on formatting reviews while the PR is marked draft? I commented in this thread last week that I'll change it to ready for review and ping you. It's not like I'm bothered or anything, but I do prefer using the draft as draft so we can discuss experimental prototypes before thinking about formatting or structure.

2025-01-14 01:20 UTC, t-sasatani commented
And thanks for the info, @raymondwjang. I think I attended that meeting, but I sent a view request because I couldn't access the slides.

I can squash commit counts later if you prefer, but I guess it is unlikely that PRs for refactoring or adding new modules (like this one) will fit in 500 lines of code. That rule makes sense for minor additions or fixes, but is it considered better for everything?

2025-01-14 01:57 UTC, raymondwjang commented
shared! obviously there are reasonable violations to the rule, but simply seeing 1000+ lines on a PR is pretty threatening as a reviewer. 

even within enterprise level large projects, massive PRs are rare unless there's a sweeping feature change or a massive refactor, as they always introduce exponentially larger review overheads, bug risks, rollback costs, etc. Even with new files it not super common to see PRs approaching 1000 and above, and that's including the tests and documentations. Also remember that these repos are generated hosted with an extensive suite of CI/CD tools that make sure the codes are healthy. (which we don't currently have)

currently this code is 1000 lines, but with tests and documentations it might approach 2000. that can turn into hours of reviewing and still missing bugs and edge cases. i had a similar pr that grew uncontrollably, and ended up having to chop it up into 5 different PRs so that it's somewhat reviewable.

as @sneakers-the-rat can attest, i often fail to keep things nicely packaged for reviewers and future me as well. but from what i've learned, it seems like it's always recommended to keep things small, nimble and modular. do as i say not as i do lmao

2025-01-14 02:51 UTC, sneakers-the-rat commented
>  I commented in this thread last week that I'll change it to ready for review and ping you. It's not like I'm bothered or anything, but I do prefer using the draft as draft so we can discuss experimental prototypes before thinking about formatting or structure.

no problem! i was just getting started working on mio again and wanted to catch up here, draft status totally understood, giving me feedback that hopefully might help with some ideas on different ways to finalize it :)

and Raymond super appreciate the advocacy of small PRs. There are a few gigantic refactors that need to get done so i'll be guilty of a few very large PRs myself here soon enough, but once we get into a roughly stable code structure we should be able to iterate much more cleanly :).

2025-01-14 06:54 UTC, t-sasatani commented
Ok I'll try to keep these short, though I'll probably violate it sometimes. It might be easier for me to overlook review comments for draft PRs, and sry for that in advance, but if you're ok with that, I'm fine.

2025-01-15 06:55 UTC, t-sasatani commented on .gitignore
> +user_dir/*
You're talking about the user_dir? I just wanted somewhere to keep data while I work in the repo for my convenience. I'll get rid of them before getting out of draft state.

2025-01-15 06:55 UTC, t-sasatani commented on .gitignore
> +~/.config/miniscope_io/logs/
Oh this is just an accident same as above

2025-01-15 06:55 UTC, t-sasatani commented on mio/data/config/process/denoise_example.yml
> +mio_version: 0.6.1.dev16+g6436633.d20241211
Maybe something upstream in the config PR? We can probably keep this and adjust it later after the config stuff is fixed?

2025-01-15 06:55 UTC, t-sasatani commented on mio/io.py
> +class VideoWriter:
Yeah just pulled this out from stream daq without thinking much hre

2025-01-15 06:55 UTC, t-sasatani commented on mio/io.py
> +        self.width = int(self.cap.get(cv2.CAP_PROP_FRAME_WIDTH))
If we want flexibility here, that makes sense, but as we probably don't want it wouldn't that just be harmful? I was thinking of one instance per video path here.

2025-01-15 06:55 UTC, t-sasatani commented on mio/models/frames.py
> +    video_frame: Optional[List[np.ndarray]] = Field(
Yeah that side of the repo is a mystery to me and we can leave that for a pure refactor PR

2025-01-15 06:55 UTC, t-sasatani commented on mio/models/frames.py
> +    )
Oh yeah, I was wondering how to handle truncated videos and distinguish a stack of frames coming from truncated videos and a regular video clip. This is something I was going to clean up by just making separate models for these.

2025-01-15 06:55 UTC, t-sasatani commented on mio/models/frames.py
> +    frame_type: Optional[str] = Field(
as the above just truncated videos, something that just grew while sketching out and awaiting cleanum

2025-01-15 06:55 UTC, t-sasatani commented on mio/models/process.py
> +    Configuration for patch based noise handling.
Yup palnned

2025-01-15 07:24 UTC, t-sasatani commented on mio/process/video.py
> +    def denoise(
Yeah, it's literally just a raw script disguised as some class now. I'll try to be more explicit that these aren't awaiting formatting review or avoid uploading PRs in draft status so we don't double labor on both ends.

2025-01-15 08:20 UTC, t-sasatani commented on .gitignore
> +user_dir/*
Oh I forgot user_dir is used for config. I might keep a user_data dir just for convenience in dev.

2025-01-15 14:28 UTC, t-sasatani commented on tests/test_models/test_model_process.py
> +    config = DenoiseConfig.from_id("denoise_test").interactive_display
@sneakers-the-rat, it might be in docs somewhere, but could you let me know how to find these configurations in the test dir? I'm putting it into the same directory as the test config for stream DAQ, but getting this. Do you need some registering or anything?

>No config with id denoise_test found in /path/to/somewhere/Application Support/mio/config

2025-01-15 16:38 UTC, t-sasatani commented
I'm switching this to ready for review as I'm heading home. I'm sorry it's becoming gigantic.

It's done structure-wise, and I changed the patch frame function to drop frames and added a tracking/export thing.

\I haven't gone through the reviews yet, more documents/tests need to be completed, and the interfaces, like the naming of the export paths, are unsettled, so I'll return to them later this week. If you want to take over or make a significant change in the meantime, feel free to go ahead

2025-01-15 16:52 UTC, t-sasatani commented on tests/test_models/test_model_process.py
> +    config = DenoiseConfig.from_id("denoise_test").interactive_display
Just leaving a note here so I don't forget I'm skipping these config tests for now.

2025-01-16 06:44 UTC, sneakers-the-rat commented on tests/test_models/test_model_process.py
> +    config = DenoiseConfig.from_id("denoise_test").interactive_display
In general I don't think we need these kinda tests (if we wanted to ensure that these values don't change, we could just copy it to tests and assert that the copy in tests was equal to the one in the package), but the fact that it isn't being found would be a bug with the config discovery methods or how we are monkeypatching them to include the `tests/data/config` directory during testing. i'll check this out in the morning

2025-01-16 06:47 UTC, sneakers-the-rat commented on .gitignore
> +user_dir/*
up to you where you want to put it, no problem having an extra line in .gitignore. 

if you wanted this to persist you would set `user_dir` in the global config for your machine (`mio config global path`)

2025-01-16 06:54 UTC, sneakers-the-rat commented on mio/io.py
> +        self.width = int(self.cap.get(cv2.CAP_PROP_FRAME_WIDTH))
yeah that should be the expected pattern, but just general "best practices" object oriented design, it is *possible* and conceivable that someone would manually change `video_path`, and doing stuff with properties is one way of handling state changes like that - always read from the current thing by programming dependencies between attributes. i would say comparatively minor so don't worry abt it

2025-01-16 06:58 UTC, sneakers-the-rat commented on mio/process/frame_helper.py
> +class ZStackHelper:
i like this idea :)

2025-01-16 07:01 UTC, sneakers-the-rat commented on mio/process/frame_helper.py
> +    def split_by_length(self, array: np.ndarray, segment_length: int) -> list[np.ndarray]:
something like this seems pretty general purpose, but we don't have a good place to put 'general array manipulation functions' like a utils junk drawer would be. i like this helper class idea, bundling some operations together with some staticmethods. i get where this is coming from being split off from the previous implementation, so i'm fine with this, but in the future i might want to play with this helper class idea, make it its own module, and make some generic "ArrayHelper"/"BufferHelper" kind of classes

2025-02-02 07:54 UTC, t-sasatani commented on mio/io.py
> +        self.width = int(self.cap.get(cv2.CAP_PROP_FRAME_WIDTH))
Switched to @property

2025-02-02 07:55 UTC, t-sasatani commented on mio/io.py
> +    def release(self) -> None:
Yea this is fragile, as you say. Switched to property

2025-02-02 07:56 UTC, t-sasatani commented on mio/models/frames.py
> +T = TypeVar("T", np.ndarray, List[np.ndarray], List[List[np.ndarray]])
Just split out video and frame classes here because it's not really necessary to unify them.

2025-02-02 07:56 UTC, t-sasatani commented on mio/models/frames.py
> +    )
Just made separate models for these

2025-02-02 07:57 UTC, t-sasatani commented on mio/models/frames.py
> +    video_frame: Optional[List[np.ndarray]] = Field(
Split out classes to make it bit more explicit

2025-02-02 07:57 UTC, t-sasatani commented on mio/models/frames.py
> +    frame_type: Optional[str] = Field(
Got rid of this

2025-02-02 08:02 UTC, t-sasatani commented on mio/models/process.py
> +    )
Seems like it was done in one of the attached PRs

2025-02-02 08:06 UTC, t-sasatani commented on mio/models/process.py
> +    )
The line-by-line approach seems simpler, so let's make that the default. I will leave this actual buffer-wise comparison approach as a non-recommended option because it will likely be more accurate.

2025-02-02 08:08 UTC, t-sasatani commented on mio/models/process.py
> +    )
Got it. I will skip it here.

2025-02-02 08:09 UTC, t-sasatani commented on mio/plots/video.py
> +        videos: List[NamedFrame],
Done by splitting out NamedFrame and Video classes

2025-02-02 08:12 UTC, t-sasatani commented on mio/process/video.py
> +        self.height = height
I guess everything except for the spacial freq mask can be done that way. Will switch.

2025-02-02 08:25 UTC, t-sasatani commented on mio/process/video.py
> +class FrameProcessor:
I guess it's now kind of like this.

2025-02-02 08:29 UTC, t-sasatani commented on mio/process/video.py
> +    def split_by_length(self, array: np.ndarray, segment_length: int) -> list[np.ndarray]:
I didn't notice that `numpy.split` can do this kind of split with 1-D array indexes. Will switch.

2025-02-02 08:47 UTC, t-sasatani commented on mio/process/video.py
> +                i = buffer_index * noise_patch_config.buffer_split + split_index
Yeah this is confusing in general having splitting and processing mixed. Will change structure here.

2025-02-02 08:56 UTC, t-sasatani commented on mio/process/video.py
> +        return mask
Yeah, moved to the model. I think we might want some interactive display option before the actual processing happens.

2025-02-02 09:08 UTC, t-sasatani commented on mio/process/video.py
> +            freq_filtered_frames = []
I think it's kind of like this now

2025-02-02 09:08 UTC, t-sasatani commented on mio/process/video.py
> +            subtract_minimum = VideoProcessor.normalize_video_stack(subtract_minimum)
Done

2025-02-02 09:14 UTC, t-sasatani commented on mio/process/video.py
> +                        img=patched_frame,
I wish I could pass down pointers here. It's slightly better now, but it still uses extra memory if the processing isn't enabled (and, of course, it is pretty inefficient inside the helpers).

2025-02-02 09:16 UTC, t-sasatani commented on mio/process/video.py
> +        finally:
I think it's now like this. It might be better to release memory if it gets more integrated with other stuff, but I guess just having export stuff is fine while this is an independent module.

2025-02-02 09:20 UTC, t-sasatani commented on mio/process/video.py
> +
Yeah makes sense. This will be mainly for debugging, as the interactive plot gets very slow after a few hundred frames. I guess I'll put non-user facing stuff in the debug section of the config.

2025-02-02 09:21 UTC, t-sasatani commented on mio/process/video.py
> +    def normalize_video_stack(image_list: list[np.ndarray]) -> list[np.ndarray]:
Done

2025-02-02 09:23 UTC, t-sasatani commented on mio/process/frame_helper.py
> +    def split_by_length(self, array: np.ndarray, segment_length: int) -> list[np.ndarray]:
Yeah, that does make sense. After all, this whole package is about tinkering with numpy arrays not just this denoising module.

2025-02-02 10:37 UTC, t-sasatani commented on mio/models/process.py
> +    )
I changed it a bit so this gets calculated from the device config that acquired this stream.

2025-02-02 11:07 UTC, t-sasatani commented on mio/models/process.py
> +    )
done

2025-02-02 11:07 UTC, t-sasatani commented on mio/models/process.py
> +        description="Radius for the spatial cutoff.",
added

2025-02-02 11:08 UTC, t-sasatani commented on mio/models/process.py
> +        description="Frame to end processing at.",
added

2025-02-02 11:26 UTC, t-sasatani commented on mio/process/video.py
> +                        img=patched_frame,
Well at least the input isn't copied now so will resolve it

2025-02-02 11:29 UTC, t-sasatani commented on mio/plots/video.py
> +            ax.axis("off")
Haven't brought it to the level it can be used with streamdaq but at least chunked it up in units that hopefully make sense.

2025-02-02 11:32 UTC, t-sasatani commented on mio/plots/video.py
> +        fig, axes = plt.subplots(1, num_streams, figsize=(20, 5))
Not exactly sure what this was because it's pretty outdated, but it doesn't have to be actually interactive and doing `draw_idle()` whenever GUI gets released seems fine.

2025-02-02 11:32 UTC, t-sasatani commented on mio/plots/video.py
> +    def show_video_with_controls(
Yes done this

2025-02-02 11:33 UTC, t-sasatani commented on mio/models/process.py
> +    Configuration for patch based noise handling.
Done

2025-02-02 13:58 UTC, t-sasatani commented on mio/process/video.py
> +            for split_index in range(noise_patch_config.buffer_split):
I fixed the code to look at pixel chunks that accumulate from the end of the buffer (i.e., how the error is likely to happen). But anyway, the mean_error approach is unstable, and I posted a warning not to use it.

2025-02-02 13:58 UTC, t-sasatani commented on mio/process/video.py
> +                i = buffer_index * noise_patch_config.buffer_split + split_index
Done

2025-02-02 14:00 UTC, t-sasatani commented on mio/process/video.py
> +    def patch_noisy_buffer(
I think I'll leave this for later as the mean_error approach won't be used for now.

2025-02-02 14:05 UTC, t-sasatani commented on mio/models/process.py
> +    )
Done

2025-02-02 14:41 UTC, t-sasatani commented
Thanks for all the feedback. I might have missed something, but I went through all the comments. 
- We should make `gradient` the primary noise detection approach, but I am also thinking about leaving the `mean_error` method in case (probably until we start benchmarking stuff and combining methods). This does make the helper methods slightly more complex so let me know if I should move this to a different branch or something.
- I think the YAML interface and export path need improvement, but that's pretty minor, so I think we can push that later.

2025-02-16 07:27 UTC, t-sasatani commented
Just failing at coverage reports. Probably because Coveralls is down for maintenance.

2025-07-22 02:51 UTC, sneakers-the-rat reviewed
nice. ok i'm good with all this except for one thing in the tests which will cause us trouble down the line, give me one second to update it, then i'll throw it back to @t-sasatani , and then after resolving last questions we should be good to go

2025-07-22 02:51 UTC, sneakers-the-rat commented on mio/io.py
> +            output_dict["-r"] = str(fps)
```suggestion
    """
    Write data to a video file using FFMpegWriter.
    """
    
    DEFAULT_OUTPUT = {
        "-vcodec": "rawvideo",
        "-f": "avi",
        "-filter:v": "format=gray",
    }

    def __init__(
        self,
        path: Union[str, Path],
        fps: int,
        output_dict: Union[dict, None] = None,
    ):
        """
        Initialize the VideoWriter object.
        """
        if output_dict is None:
            output_dict = {}
        output_dict = {**self.DEFAULT_OUTPUT, **output_dict}
        output_dict["-r"] = str(fps)
```

another way you could do this, the `output_dict` will be merged with (and override) any values in the default. makes it so if we want to override one parameter we don't need to override all of them, and makes the default values accessible outside the init method

2025-07-22 02:51 UTC, sneakers-the-rat commented on mio/io.py
> +    def read_frames(self) -> Iterator[Tuple[int, np.ndarray]]:
nice!

2025-07-22 02:51 UTC, sneakers-the-rat commented on mio/models/frames.py
> +        arbitrary_types_allowed=True,
this is what numpydantic is for :)

2025-07-22 02:51 UTC, sneakers-the-rat commented on mio/models/frames.py
> +        Display the frame data.
probably want to say "opens an opencv window. to close the window press escape" (i think that's what waitkey 27 is?)

2025-07-22 02:51 UTC, sneakers-the-rat commented on mio/models/frames.py
> +        Export the frame data to a file.
maybe a little bit of a description about how the `name` relates to the output path here - like i would expect if i passed an `output_path` here that would mean i call this like `video.export(Path('/home/jonny/myvideo.avi'))` and for the video to be saved there, but it would actually be saved in a different location that includes the name. so just in the docs let's just describe how the output_path is used

2025-07-22 02:51 UTC, sneakers-the-rat commented on mio/models/process.py
> +        description="Threshold for detecting invalid frames based on mean squared error.",
range of this threshold? 0-1?

2025-07-22 02:51 UTC, sneakers-the-rat commented on mio/models/process.py
> +    buffer_size: int = Field(
should probably come from the device config, no? seems like we run the risk of double-configuring with conflicting params by passing the device config as well as buffer size.

2025-07-22 02:51 UTC, sneakers-the-rat commented on mio/models/process.py
> +    def device_config(self) -> StreamDevConfig:
nice

2025-07-22 02:51 UTC, sneakers-the-rat commented on mio/models/process.py
> +    )
what happens when these are `None`?

2025-07-22 02:51 UTC, sneakers-the-rat commented on mio/plots/video.py
> +class VideoPlotter:
raise issue to fix problems with needing to store videos in memory by using numpydantic

2025-07-22 02:51 UTC, sneakers-the-rat commented on tests/test_models/test_model_frames.py
> +    unittest.main()
```suggestion

```

2025-07-22 02:51 UTC, sneakers-the-rat commented on tests/test_plots/test_plots_video.py
> +    def test_show_video_with_controls(self, MockButton, MockSlider, mock_subplots, mock_show):
this doesn't *really* test anything important about this class, but since it's not mission critical and something we will take out and put in a separate GUI package anyway, fine for now.

2025-07-22 02:51 UTC, sneakers-the-rat commented on tests/test_plots/test_plots_video.py
> +        self.assertEqual(len(mock_axes), len(self.named_frames))
classic LLM assertion that tests nothing

2025-07-22 02:51 UTC, sneakers-the-rat commented on tests/test_plots/test_plots_video.py
> +    unittest.main()
```suggestion

```

2025-07-22 02:51 UTC, sneakers-the-rat commented on tests/test_process_video.py
> +        self.test_dir = Path("/tmp/test_output")
not portable across OS, unfortunately, and likely to hit some existing directory this way. this is why we use the `tmp_path` pytest fixture https://docs.pytest.org/en/latest/how-to/tmp_path.html

2025-07-22 02:51 UTC, sneakers-the-rat commented on tests/test_process_video.py
> +        self.test_dir = Path("/tmp/test_output")
this would also need to get removed on teardown

2025-07-22 02:51 UTC, sneakers-the-rat commented on tests/test_process_video.py
> +        self.test_dir = Path("/tmp/test_output")
i'm actually just going to rewrite these with pytest

2025-07-22 02:51 UTC, sneakers-the-rat commented on tests/test_stream_daq.py
> +                "ee7bdb97c1e98ebeefc65ae651968e3a72d099e57d1fdec5ec05a3598733db93",
hell yes.

2025-07-22 03:14 UTC, sneakers-the-rat commented
ok this is just about my minimum for "is this PR tested" - i think all the core behavior has *basic* tests, but there is a bunch of accessory code that is untested - like the plotting widget, the wrappers around all the intermediate processing stages, their outputs, etc. but i'm fine with it for now since a lot of that is just wrapping the core behavior in `process/frame_helpers`

the thing that I don't really love is that we now have two sets of models for images and frames: `models.data` and `models.frames` - that shouldn't last long, and i'll raise a followup issue for that (raised #118)

2025-07-22 03:35 UTC, t-sasatani commented on mio/io.py
> +            output_dict["-r"] = str(fps)
Totally makes sense

2025-07-22 03:36 UTC, t-sasatani commented on mio/models/frames.py
> +        arbitrary_types_allowed=True,
Yeah this is pretty annoying. Definitely next PR!

2025-07-22 03:37 UTC, t-sasatani commented on mio/models/frames.py
> +        Display the frame data.
Yes exactly, will do.

2025-07-22 03:45 UTC, t-sasatani commented on mio/models/frames.py
> +        Export the frame data to a file.
Added that note in the docstring. Also unsure if just jamming the name into the suffix is good as we chatted but let's think later.

2025-07-22 03:47 UTC, t-sasatani commented on mio/models/process.py
> +        description="Threshold for detecting invalid frames based on mean squared error.",
Just raw mean square error (not normalized), so it's any positive number or zero.

2025-07-22 03:49 UTC, t-sasatani commented on mio/models/process.py
> +        description="Threshold for detecting invalid frames based on mean squared error.",
Added a note anyway

2025-07-22 03:58 UTC, t-sasatani commented on mio/models/process.py
> +    buffer_size: int = Field(
Good catch. I changed it based on the device config already, but forgot to delete this field. Just deleted now

2025-07-22 04:12 UTC, t-sasatani commented on tests/test_models/test_model_frames.py
> +    unittest.main()
Don't know why it's not auto-resolved, but removed this entry point

2025-07-22 04:14 UTC, t-sasatani commented on tests/test_plots/test_plots_video.py
> +    def test_show_video_with_controls(self, MockButton, MockSlider, mock_subplots, mock_show):
Makes sense. Not exactly sure how to test widgets at the moment, but can do it later if we're isolating this.

2025-07-22 04:18 UTC, t-sasatani commented on tests/test_plots/test_plots_video.py
> +        self.assertEqual(len(mock_axes), len(self.named_frames))
Yeah I guess the called times is the only ones that make sense here

2025-07-22 04:18 UTC, t-sasatani commented on tests/test_process_video.py
> +        self.test_dir = Path("/tmp/test_output")
Nice thanks!

2025-07-22 04:50 UTC, t-sasatani commented on mio/models/process.py
> +    )
Actually, these caused problems. I added some tests to bind that.

2025-07-22 04:53 UTC, t-sasatani commented on mio/plots/video.py
> +class VideoPlotter:
Added note here to not forget. #119

2025-07-22 05:31 UTC, t-sasatani commented
Thanks for checking throughout! I think I've addressed the comments. My bad that I didn't notice the data model. We should definitely get rid of the duplicate soon.

I guess I'll wait for @sneakers-the-rat 's approval, as it feels bad to bypass rules after this gigantic PR for some reason.

2025-07-22 05:47 UTC, t-sasatani commented on mio/models/frames.py
> +        Display the frame data.
added

2025-07-22 06:42 UTC, sneakers-the-rat commented on tests/test_process/test_video.py
> +    assert processed_frame is random_8bit_video_frame
thx for this

2025-07-22 06:50 UTC, t-sasatani commented
Sure! Thanks for looking into it again.

2025-07-22 06:50 UTC, merged